# Site settings
title: battleflag.me
email: your-email@domain.com
baseurl: http://iamgfawkes.github.io/battleflag.me
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#793130'

# Footer settings
footer: battleflag.me

# Build settings
markdown: kramdown
permalink: pretty
